services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    expose:
      - "8443"
    volumes:
      - ./conf/Caddyfile:/etc/caddy/Caddyfile

  nginx:
    build:
      context: .
    container_name: nginx-patched
    restart: unless-stopped
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - DOMAIN_NAME=${DOMAIN_NAME}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
      - ./static:/etc/nginx/static:ro
      - ./acme-state:/etc/nginx/acme-state
