services:
  anubis:
    image: ghcr.io/techarohq/anubis:latest
    container_name: anubis
    environment:
      BIND: "/run/anubis/sockets/anubis.sock"
      BIND_NETWORK: "unix"
      SOCKET_MODE: "0777"
      TARGET: "unix:///run/anubis/sockets/nginx.sock"
      # Block requests that use the public ip of the server
      REDIRECT_DOMAINS: ${DOMAIN_NAME}
      # Default configuration with difficulty pinned to 4 everywhere
      POLICY_FNAME: "/data/cfg/botPolicy.yaml"
    volumes:
      - ./sockets:/run/anubis/sockets
      - ./conf/botPolicy.yaml:/data/cfg/botPolicy.yaml:ro

  nginx:
    build:
      context: .
    container_name: nginx-patched
    restart: unless-stopped
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
      DOMAIN_NAME: ${DOMAIN_NAME}
      CADDY_1: ${CADDY_1}
      CADDY_2: ${CADDY_2}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
      - ./static:/etc/nginx/static:ro
      - ./acme-state:/etc/nginx/acme-state
      - ./cache:/etc/nginx/cache
      - ./sockets:/run/nginx/sockets
    depends_on:
      - anubis
