services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - MASTER_IP=${MASTER_IP}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf:/etc/caddy
